[package]
name = "reverso-to-anki"
version = "0.1.0"
edition = "2024"

[dependencies]
genanki-rs = "0.4.0"
scraper = "0.23.1"
serde = "1.0.219"
serde_json = "1.0.141"
thirtyfour = "0.36.1"
tokio = { version = "1.46.1", features = ["full"] }
toml = "^0.9.2"
